import { useState } from "react";
import { ArrowRight, Database, GitBranch, ListChecks, ShieldCheck, Users, Zap } from "lucide-react";

import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const TABS = ["Field & Value Map", "Query Journey", "Automation Rules", "CRM Data Model"] as const;

type Tab = (typeof TABS)[number];

const fieldRows = [
  ["Identity", "Query ID", "System", "Generated by createLead() in CRM store."],
  ["Identity", "Lead ID", "System", "Linked identifier generated with the query."],
  ["Source", "Lead Source", "User", "Stored directly on CrmQuery.lead_source."],
  ["Source", "Customer / Partner", "User", "Stored in CrmQuery.customer."],
  ["Contact", "Contact Person", "User", "Stored in CrmQuery.contact_person."],
  ["Contact", "Mobile", "User", "Stored in CrmQuery.mobile."],
  ["Contact", "Email", "User", "Stored in CrmQuery.email."],
  ["Requirement", "Requirement", "User", "Stored in CrmQuery.requirement."],
  ["Travel", "Travel Start", "User", "Stored in CrmQuery.travel_start."],
  ["Travel", "Travel End", "User", "Stored in CrmQuery.travel_end."],
  ["Travel", "Destination", "User", "Stored in CrmQuery.destination."],
  ["Travel", "Pax", "User", "Stored in CrmQuery.pax."],
  ["Commercial", "Query Value", "CRM", "Stored in CrmQuery.value and updated through CRM actions."],
  ["Ownership", "Owner", "CRM", "Connected to Employee Register via employee.name."],
  ["Workflow", "Stage", "CRM", "Changed through setQueryStage()."],
  ["Workflow", "Next Action", "CRM", "Stored in CrmQuery.next_action."],
  ["Follow-up", "Follow-up Due", "CRM", "Stored in CrmQuery.followup_due."],
  ["Audit", "Activity", "CRM Event", "Stored in the central CRM event stream."],
  ["Closure", "Won / Lost", "CRM", "Final stage on the same CrmQuery record."],
];

const journey = [
  {
    number: "01",
    title: "New",
    description:
      "Lead is created through the existing New Lead flow. Query ID, owner, activity and the first review task are created together.",
  },
  {
    number: "02",
    title: "Requirement Review",
    description:
      "Advisor reviews the requirement, destination, traveller profile and expected commercial scope.",
  },
  {
    number: "03",
    title: "Costing",
    description:
      "Itinerary and commercial preparation continues while the query remains inside the same CRM record.",
  },
  {
    number: "04",
    title: "Quotation Sent",
    description:
      "Quotation activity is logged and the query moves into a stronger follow-up stage.",
  },
  {
    number: "05",
    title: "Follow-up / Nurturing",
    description:
      "Owner controls the next client touchpoint using the central follow-up fields and event log.",
  },
  {
    number: "06",
    title: "Won",
    description:
      "The query reaches a successful final outcome and remains available for historical reporting.",
  },
  {
    number: "07",
    title: "Lost",
    description:
      "The query reaches a closed outcome while its previous activities and assignment history remain preserved.",
  },
];

const rules = [
  {
    title: "Lead Creation",
    icon: <ListChecks className="h-5 w-5" />,
    items: [
      "Existing New Lead module remains the creation interface.",
      "createLead() creates the query in crm/store.ts.",
      "A first activity is recorded.",
      "A lead assignment event is recorded.",
      "The initial review task is created for the owner.",
    ],
  },
  {
    title: "Stage Automation",
    icon: <GitBranch className="h-5 w-5" />,
    items: [
      "setQueryStage() updates the stage.",
      "Every stage transition is recorded as a CRM event.",
      "Stage duration is calculated from previous stage entry.",
      "Quotation Sent creates a quotation activity event.",
      "Won and Lost are treated as final stages.",
    ],
  },
  {
    title: "Follow-up Automation",
    icon: <Zap className="h-5 w-5" />,
    items: [
      "scheduleFollowup() creates or reschedules the next commitment.",
      "completeFollowup() records completion.",
      "logFollowup() records the actual conversation/follow-up.",
      "Overdue follow-ups are detected by the live watcher.",
      "Escalations are surfaced through useCrmMetrics().",
    ],
  },
  {
    title: "Assignment",
    icon: <Users className="h-5 w-5" />,
    items: [
      "Employee data comes from the central Employee Register.",
      "reassignQuery() records assignment changes.",
      "Previous owner information remains in event history.",
      "Open tasks follow the new owner during reassignment.",
    ],
  },
];

const dataModel = [
  {
    title: "crm/store.ts",
    description: "Single source of truth for queries, tasks, employees and events.",
  },
  {
    title: "crm/metrics.ts",
    description:
      "Single reporting layer used by dashboards, analytics, workload and escalation views.",
  },
  {
    title: "CrmQuery",
    description:
      "Current state of the enquiry including owner, stage, travel, commercial value and follow-up.",
  },
  {
    title: "CrmTask",
    description: "Actionable task connected to a query and owned by an employee.",
  },
  {
    title: "CrmEvent",
    description:
      "Audited timeline for assignments, calls, notes, stage changes, follow-ups and tasks.",
  },
  {
    title: "Employee",
    description: "Employee Register record used throughout assignments and performance views.",
  },
];

export default function WorkflowFields() {
  const [tab, setTab] = useState<Tab>("Field & Value Map");

  return (
    <div className="mx-auto max-w-[1600px] space-y-6 p-6 lg:p-8">
      {/* HEADER */}
      <div>
        <p className="text-sm font-medium text-muted-foreground">Query Management</p>

        <h1 className="mt-1 text-2xl font-bold">Workflow & Developer Blueprint</h1>

        <p className="mt-1 text-sm text-muted-foreground">
          Query Management behaviour mapped to the existing CRM data model.
        </p>
      </div>

      {/* ARCHITECTURE */}
      <Card className="rounded-xl">
        <CardContent className="p-5">
          <div className="flex items-center gap-3">
            <Database className="h-5 w-5" />

            <div>
              <h2 className="font-semibold">Single CRM Architecture</h2>

              <p className="text-xs text-muted-foreground">
                Query Management does not maintain a second query database.
              </p>
            </div>
          </div>

          <div className="mt-5 grid gap-3 md:grid-cols-4">
            <ArchitectureBox title="New Lead" description="Existing lead creation flow" />

            <Arrow />

            <ArchitectureBox
              title="crm/store.ts"
              description="Queries + Employees + Tasks + Events"
            />

            <Arrow />

            <ArchitectureBox
              title="crm/metrics.ts"
              description="Shared reporting and live analytics"
            />
          </div>
        </CardContent>
      </Card>

      {/* TABS */}
      <div className="flex flex-wrap gap-2">
        {TABS.map((item) => (
          <Button
            key={item}
            variant={tab === item ? "default" : "outline"}
            onClick={() => setTab(item)}
          >
            {item}
          </Button>
        ))}
      </div>

      {/* FIELD MAP */}
      {tab === "Field & Value Map" && (
        <Card className="rounded-xl">
          <CardContent className="p-0">
            <div className="overflow-x-auto">
              <table className="w-full min-w-[900px] text-sm">
                <thead>
                  <tr className="border-b bg-muted/30 text-left text-xs uppercase tracking-wide text-muted-foreground">
                    <th className="p-3">Group</th>

                    <th className="p-3">Field</th>

                    <th className="p-3">Source</th>

                    <th className="p-3">Behaviour</th>
                  </tr>
                </thead>

                <tbody>
                  {fieldRows.map(([group, field, source, behaviour]) => (
                    <tr key={`${group}-${field}`} className="border-b last:border-0">
                      <td className="p-3 font-medium">{group}</td>

                      <td className="p-3">{field}</td>

                      <td className="p-3">
                        <Badge variant="outline">{source}</Badge>
                      </td>

                      <td className="p-3 text-muted-foreground">{behaviour}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}

      {/* JOURNEY */}
      {tab === "Query Journey" && (
        <Card className="rounded-xl">
          <CardContent className="p-5">
            <div className="space-y-4">
              {journey.map((item, index) => (
                <div key={item.number} className="flex gap-4">
                  <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-primary text-sm font-semibold text-primary-foreground">
                    {item.number}
                  </div>

                  <div className="flex-1 rounded-xl border p-4">
                    <div className="flex items-center justify-between gap-3">
                      <h3 className="font-semibold">{item.title}</h3>

                      {index < journey.length - 1 && (
                        <ArrowRight className="h-4 w-4 text-muted-foreground" />
                      )}
                    </div>

                    <p className="mt-1 text-sm text-muted-foreground">{item.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* RULES */}
      {tab === "Automation Rules" && (
        <div className="grid gap-5 md:grid-cols-2">
          {rules.map((rule) => (
            <Card key={rule.title} className="rounded-xl">
              <CardContent className="p-5">
                <div className="flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-muted">
                    {rule.icon}
                  </div>

                  <h3 className="font-semibold">{rule.title}</h3>
                </div>

                <div className="mt-4 space-y-3">
                  {rule.items.map((item) => (
                    <div key={item} className="flex gap-2 text-sm">
                      <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />

                      <span className="text-muted-foreground">{item}</span>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* DATA MODEL */}
      {tab === "CRM Data Model" && (
        <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
          {dataModel.map((item) => (
            <Card key={item.title} className="rounded-xl">
              <CardContent className="p-5">
                <div className="flex items-center gap-3">
                  <Database className="h-5 w-5" />

                  <h3 className="font-semibold">{item.title}</h3>
                </div>

                <p className="mt-3 text-sm text-muted-foreground">{item.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* GUARDRAIL */}
      <Card className="rounded-xl border-emerald-200">
        <CardContent className="flex gap-3 p-5">
          <ShieldCheck className="mt-0.5 h-5 w-5 text-emerald-600" />

          <div>
            <h3 className="font-semibold">Architecture Guardrail</h3>

            <p className="mt-1 text-sm text-muted-foreground">
              Query Management should read and mutate the existing CRM records only. Do not create
              another local query store, employee store or analytics source.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function ArchitectureBox({ title, description }: { title: string; description: string }) {
  return (
    <div className="rounded-xl border bg-muted/20 p-4">
      <p className="font-semibold">{title}</p>

      <p className="mt-1 text-xs text-muted-foreground">{description}</p>
    </div>
  );
}

function Arrow() {
  return (
    <div className="hidden items-center justify-center md:flex">
      <ArrowRight className="h-5 w-5 text-muted-foreground" />
    </div>
  );
}
