/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRateSearchRouteImport } from './routes/_authenticated/rate-search'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCostingRouteImport } from './routes/_authenticated/costing'
import { Route as AuthenticatedHotelsIndexRouteImport } from './routes/_authenticated/hotels/index'
import { Route as AuthenticatedHotelsIdRouteImport } from './routes/_authenticated/hotels/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRateSearchRoute = AuthenticatedRateSearchRouteImport.update({
  id: '/rate-search',
  path: '/rate-search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostingRoute = AuthenticatedCostingRouteImport.update({
  id: '/costing',
  path: '/costing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHotelsIndexRoute =
  AuthenticatedHotelsIndexRouteImport.update({
    id: '/hotels/',
    path: '/hotels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotelsIdRoute = AuthenticatedHotelsIdRouteImport.update({
  id: '/hotels/$id',
  path: '/hotels/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/costing': typeof AuthenticatedCostingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rate-search': typeof AuthenticatedRateSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/hotels/$id': typeof AuthenticatedHotelsIdRoute
  '/hotels/': typeof AuthenticatedHotelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/costing': typeof AuthenticatedCostingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rate-search': typeof AuthenticatedRateSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/hotels/$id': typeof AuthenticatedHotelsIdRoute
  '/hotels': typeof AuthenticatedHotelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/costing': typeof AuthenticatedCostingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/rate-search': typeof AuthenticatedRateSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/hotels/$id': typeof AuthenticatedHotelsIdRoute
  '/_authenticated/hotels/': typeof AuthenticatedHotelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/costing'
    | '/dashboard'
    | '/rate-search'
    | '/settings'
    | '/hotels/$id'
    | '/hotels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/costing'
    | '/dashboard'
    | '/rate-search'
    | '/settings'
    | '/hotels/$id'
    | '/hotels'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/costing'
    | '/_authenticated/dashboard'
    | '/_authenticated/rate-search'
    | '/_authenticated/settings'
    | '/_authenticated/hotels/$id'
    | '/_authenticated/hotels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rate-search': {
      id: '/_authenticated/rate-search'
      path: '/rate-search'
      fullPath: '/rate-search'
      preLoaderRoute: typeof AuthenticatedRateSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costing': {
      id: '/_authenticated/costing'
      path: '/costing'
      fullPath: '/costing'
      preLoaderRoute: typeof AuthenticatedCostingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotels/': {
      id: '/_authenticated/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof AuthenticatedHotelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotels/$id': {
      id: '/_authenticated/hotels/$id'
      path: '/hotels/$id'
      fullPath: '/hotels/$id'
      preLoaderRoute: typeof AuthenticatedHotelsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCostingRoute: typeof AuthenticatedCostingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRateSearchRoute: typeof AuthenticatedRateSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedHotelsIdRoute: typeof AuthenticatedHotelsIdRoute
  AuthenticatedHotelsIndexRoute: typeof AuthenticatedHotelsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCostingRoute: AuthenticatedCostingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRateSearchRoute: AuthenticatedRateSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedHotelsIdRoute: AuthenticatedHotelsIdRoute,
  AuthenticatedHotelsIndexRoute: AuthenticatedHotelsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
