/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTravelsRouteImport } from './routes/_authenticated/travels'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRateSearchRouteImport } from './routes/_authenticated/rate-search'
import { Route as AuthenticatedQuotesRouteImport } from './routes/_authenticated/quotes'
import { Route as AuthenticatedMiscellaneousRouteImport } from './routes/_authenticated/miscellaneous'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated/guide'
import { Route as AuthenticatedEntrancesRouteImport } from './routes/_authenticated/entrances'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCostingRouteImport } from './routes/_authenticated/costing'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedHotelsIndexRouteImport } from './routes/_authenticated/hotels/index'
import { Route as AuthenticatedHotelsIdRouteImport } from './routes/_authenticated/hotels/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTravelsRoute = AuthenticatedTravelsRouteImport.update({
  id: '/travels',
  path: '/travels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRateSearchRoute = AuthenticatedRateSearchRouteImport.update({
  id: '/rate-search',
  path: '/rate-search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesRoute = AuthenticatedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiscellaneousRoute =
  AuthenticatedMiscellaneousRouteImport.update({
    id: '/miscellaneous',
    path: '/miscellaneous',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrancesRoute = AuthenticatedEntrancesRouteImport.update({
  id: '/entrances',
  path: '/entrances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostingRoute = AuthenticatedCostingRouteImport.update({
  id: '/costing',
  path: '/costing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHotelsIndexRoute =
  AuthenticatedHotelsIndexRouteImport.update({
    id: '/hotels/',
    path: '/hotels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotelsIdRoute = AuthenticatedHotelsIdRouteImport.update({
  id: '/hotels/$id',
  path: '/hotels/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/costing': typeof AuthenticatedCostingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entrances': typeof AuthenticatedEntrancesRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/miscellaneous': typeof AuthenticatedMiscellaneousRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/rate-search': typeof AuthenticatedRateSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/travels': typeof AuthenticatedTravelsRoute
  '/hotels/$id': typeof AuthenticatedHotelsIdRoute
  '/hotels/': typeof AuthenticatedHotelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/costing': typeof AuthenticatedCostingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entrances': typeof AuthenticatedEntrancesRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/miscellaneous': typeof AuthenticatedMiscellaneousRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/rate-search': typeof AuthenticatedRateSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/travels': typeof AuthenticatedTravelsRoute
  '/hotels/$id': typeof AuthenticatedHotelsIdRoute
  '/hotels': typeof AuthenticatedHotelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/costing': typeof AuthenticatedCostingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entrances': typeof AuthenticatedEntrancesRoute
  '/_authenticated/guide': typeof AuthenticatedGuideRoute
  '/_authenticated/miscellaneous': typeof AuthenticatedMiscellaneousRoute
  '/_authenticated/quotes': typeof AuthenticatedQuotesRoute
  '/_authenticated/rate-search': typeof AuthenticatedRateSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/travels': typeof AuthenticatedTravelsRoute
  '/_authenticated/hotels/$id': typeof AuthenticatedHotelsIdRoute
  '/_authenticated/hotels/': typeof AuthenticatedHotelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activities'
    | '/costing'
    | '/dashboard'
    | '/entrances'
    | '/guide'
    | '/miscellaneous'
    | '/quotes'
    | '/rate-search'
    | '/settings'
    | '/travels'
    | '/hotels/$id'
    | '/hotels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activities'
    | '/costing'
    | '/dashboard'
    | '/entrances'
    | '/guide'
    | '/miscellaneous'
    | '/quotes'
    | '/rate-search'
    | '/settings'
    | '/travels'
    | '/hotels/$id'
    | '/hotels'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/activities'
    | '/_authenticated/costing'
    | '/_authenticated/dashboard'
    | '/_authenticated/entrances'
    | '/_authenticated/guide'
    | '/_authenticated/miscellaneous'
    | '/_authenticated/quotes'
    | '/_authenticated/rate-search'
    | '/_authenticated/settings'
    | '/_authenticated/travels'
    | '/_authenticated/hotels/$id'
    | '/_authenticated/hotels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/travels': {
      id: '/_authenticated/travels'
      path: '/travels'
      fullPath: '/travels'
      preLoaderRoute: typeof AuthenticatedTravelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rate-search': {
      id: '/_authenticated/rate-search'
      path: '/rate-search'
      fullPath: '/rate-search'
      preLoaderRoute: typeof AuthenticatedRateSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes': {
      id: '/_authenticated/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/miscellaneous': {
      id: '/_authenticated/miscellaneous'
      path: '/miscellaneous'
      fullPath: '/miscellaneous'
      preLoaderRoute: typeof AuthenticatedMiscellaneousRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrances': {
      id: '/_authenticated/entrances'
      path: '/entrances'
      fullPath: '/entrances'
      preLoaderRoute: typeof AuthenticatedEntrancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costing': {
      id: '/_authenticated/costing'
      path: '/costing'
      fullPath: '/costing'
      preLoaderRoute: typeof AuthenticatedCostingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotels/': {
      id: '/_authenticated/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof AuthenticatedHotelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotels/$id': {
      id: '/_authenticated/hotels/$id'
      path: '/hotels/$id'
      fullPath: '/hotels/$id'
      preLoaderRoute: typeof AuthenticatedHotelsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedCostingRoute: typeof AuthenticatedCostingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntrancesRoute: typeof AuthenticatedEntrancesRoute
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRoute
  AuthenticatedMiscellaneousRoute: typeof AuthenticatedMiscellaneousRoute
  AuthenticatedQuotesRoute: typeof AuthenticatedQuotesRoute
  AuthenticatedRateSearchRoute: typeof AuthenticatedRateSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTravelsRoute: typeof AuthenticatedTravelsRoute
  AuthenticatedHotelsIdRoute: typeof AuthenticatedHotelsIdRoute
  AuthenticatedHotelsIndexRoute: typeof AuthenticatedHotelsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedCostingRoute: AuthenticatedCostingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntrancesRoute: AuthenticatedEntrancesRoute,
  AuthenticatedGuideRoute: AuthenticatedGuideRoute,
  AuthenticatedMiscellaneousRoute: AuthenticatedMiscellaneousRoute,
  AuthenticatedQuotesRoute: AuthenticatedQuotesRoute,
  AuthenticatedRateSearchRoute: AuthenticatedRateSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTravelsRoute: AuthenticatedTravelsRoute,
  AuthenticatedHotelsIdRoute: AuthenticatedHotelsIdRoute,
  AuthenticatedHotelsIndexRoute: AuthenticatedHotelsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
